const state={img:null, template:null, cvReady:false};
const $=id=>document.getElementById(id);
const out=(id,title,canvas,extra="")=>{const d=document.createElement("div");d.className="result-card";d.innerHTML=`<h3>${title}</h3>`;if(canvas)d.appendChild(canvas);if(extra)d.insertAdjacentHTML("beforeend",extra);$(id).appendChild(d)};
function clearOut(id){$(id).innerHTML=""}
function requireImage(){if(!state.img){alert("Please choose an image first.");return false}return true}
function makeCanvas(w,h){const c=document.createElement("canvas");c.width=w;c.height=h;return c}
function loadImage(file){const r=new FileReader();r.onload=e=>{const im=new Image();im.onload=()=>{state.img=im;state.template=null;$("fileName").textContent=file.name;resetMask();};im.src=e.target.result};r.readAsDataURL(file)}
$("imageInput").onchange=e=>e.target.files[0]&&loadImage(e.target.files[0]);
$("loadSample").onclick=()=>{const c=makeCanvas(720,480),x=c.getContext("2d");let g=x.createLinearGradient(0,0,720,480);g.addColorStop(0,"#173b5d");g.addColorStop(1,"#d78b4a");x.fillStyle=g;x.fillRect(0,0,720,480);x.fillStyle="#f4d35e";x.beginPath();x.arc(570,100,55,0,Math.PI*2);x.fill();x.fillStyle="#1f2937";x.fillRect(90,330,540,35);x.fillStyle="#f8fafc";x.fillRect(120,210,120,120);x.fillRect(300,160,140,170);x.fillStyle="#ef4444";x.beginPath();x.moveTo(60,330);x.lineTo(180,210);x.lineTo(300,330);x.fill();x.fillStyle="#16a34a";x.beginPath();x.arc(520,290,65,0,Math.PI*2);x.fill();const im=new Image();im.onload=()=>{state.img=im;$("fileName").textContent="Built-in sample image";resetMask()};im.src=c.toDataURL()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
document.querySelectorAll('input[type="range"]').forEach(x=>x.oninput=()=>{const o=x.parentElement.querySelector("output");if(o)o.value=x.value+(x.id==="angle"?"°":x.id==="scale"?"%":"")});
function baseMat(){const c=makeCanvas(state.img.naturalWidth||state.img.width,state.img.naturalHeight||state.img.height),x=c.getContext("2d");x.drawImage(state.img,0,0,c.width,c.height);return cv.imread(c)}
function showMat(id,title,mat){const c=makeCanvas(mat.cols,mat.rows);cv.imshow(c,mat);out(id,title,c);mat.delete()}
function rgbGray(){if(!requireImage())return;const m=baseMat(),g=new cv.Mat();cv.cvtColor(m,g,cv.COLOR_RGBA2GRAY);showMat("p2out","Grayscale",g);m.delete()}
document.querySelectorAll("[data-op]").forEach(b=>b.onclick=()=>{if(!requireImage())return;const op=b.dataset.op,m=baseMat();let r=new cv.Mat(),g=new cv.Mat();if(op==="gray"){cv.cvtColor(m,r,cv.COLOR_RGBA2GRAY);showMat("p2out","Grayscale",r)}else if(op==="rgb"){cv.cvtColor(m,r,cv.COLOR_RGBA2RGB);showMat("p2out","RGB representation",r)}else if(op==="add"||op==="subtract"){const s=new cv.Mat(m.rows,m.cols,m.type(),new cv.Scalar(35,35,35,0));op==="add"?cv.add(m,s,r):cv.subtract(m,s,r);showMat("p2out",op==="add"?"Arithmetic Addition":"Arithmetic Subtraction",r);s.delete()}else{const gray=new cv.Mat();cv.cvtColor(m,gray,cv.COLOR_RGBA2GRAY);const inv=new cv.Mat(gray.rows,gray.cols,gray.type(),new cv.Scalar(255));if(op==="not")cv.bitwise_not(gray,r);else if(op==="and")cv.bitwise_and(gray,inv,r);else if(op==="or")cv.bitwise_or(gray,inv,r);else cv.bitwise_xor(gray,inv,r);showMat("p2out","Bitwise "+op.toUpperCase(),r);gray.delete();inv.delete()}m.delete();clearOut("p2out")});
/* fix order: operation buttons should retain result, so rerender handler */
document.querySelectorAll("[data-op]").forEach(b=>{b.onclick=()=>{if(!requireImage())return;clearOut("p2out");const op=b.dataset.op,m=baseMat(),r=new cv.Mat();if(op==="gray")cv.cvtColor(m,r,cv.COLOR_RGBA2GRAY);else if(op==="rgb")cv.cvtColor(m,r,cv.COLOR_RGBA2RGB);else if(op==="add"||op==="subtract"){const s=new cv.Mat(m.rows,m.cols,m.type(),new cv.Scalar(35,35,35,0));op==="add"?cv.add(m,s,r):cv.subtract(m,s,r);s.delete()}else{const g=new cv.Mat();cv.cvtColor(m,g,cv.COLOR_RGBA2GRAY);if(op==="not")cv.bitwise_not(g,r);else{const inv=new cv.Mat(g.rows,g.cols,g.type(),new cv.Scalar(255));if(op==="and")cv.bitwise_and(g,inv,r);if(op==="or")cv.bitwise_or(g,inv,r);if(op==="xor")cv.bitwise_xor(g,inv,r);inv.delete()}g.delete()}showMat("p2out",op==="gray"?"Grayscale":op==="rgb"?"RGB":op==="add"?"Addition +35":op==="subtract"?"Subtraction 35":"Bitwise "+op.toUpperCase(),r);m.delete()}});
function transform(type){if(!requireImage())return;clearOut("p3out");const m=baseMat(),r=new cv.Mat(),w=m.cols,h=m.rows; if(type==="translate"){const M=cv.matFromArray(2,3,cv.CV_64F,[1,0,+$("tx").value,0,1,+$("ty").value]);cv.warpAffine(m,r,M,new cv.Size(w,h));M.delete()}else if(type==="rotate"){const M=cv.getRotationMatrix2D(new cv.Point(w/2,h/2),+$("angle").value,1);cv.warpAffine(m,r,M,new cv.Size(w,h));M.delete()}else if(type==="scale"){const s=+$("scale").value/100;cv.resize(m,r,new cv.Size(Math.round(w*s),Math.round(h*s)))}else if(type==="shear"){const sh=+$("shear").value/100;const M=cv.matFromArray(2,3,cv.CV_64F,[1,sh,0,0,1,0]);cv.warpAffine(m,r,M,new cv.Size(w,h));M.delete()}else if(type==="reflect"){cv.flip(m,r,1)}else{const rw=Math.max(2,Math.floor(w*.6)),rh=Math.max(2,Math.floor(h*.6));r.create(rh,rw,m.type());m.roi(new cv.Rect(Math.floor((w-rw)/2),Math.floor((h-rh)/2),rw,rh)).copyTo(r)}showMat("p3out",type[0].toUpperCase()+type.slice(1),r);m.delete()}
document.querySelectorAll("[data-transform]").forEach(b=>b.onclick=()=>transform(b.dataset.transform));
function enhance(type){if(!requireImage())return;clearOut("p4out");const m=baseMat(),g=new cv.Mat(),r=new cv.Mat();cv.cvtColor(m,g,cv.COLOR_RGBA2GRAY);if(type==="hist")cv.equalizeHist(g,r);else if(type==="smooth")cv.GaussianBlur(g,r,new cv.Size(7,7),0);else if(type==="sharp"){const k=cv.matFromArray(3,3,cv.CV_32F,[0,-1,0,-1,5,-1,0,-1,0]);cv.filter2D(g,r,cv.CV_8U,k);k.delete()}else cv.threshold(g,r,+$("threshold").value,255,cv.THRESH_BINARY);showMat("p4out",type==="hist"?"Histogram Equalization":type==="smooth"?"Smoothing":type==="sharp"?"Sharpening":"Thresholding",r);m.delete();g.delete()}
document.querySelectorAll("[data-enhance]").forEach(b=>b.onclick=()=>enhance(b.dataset.enhance));
function spatial(type){if(!requireImage())return;clearOut("p5out");const m=baseMat(),r=new cv.Mat(),k=+$("kernel").value;if(type==="average")cv.blur(m,r,new cv.Size(k,k));if(type==="gaussian")cv.GaussianBlur(m,r,new cv.Size(k,k),0);if(type==="median")cv.medianBlur(m,r,k);if(type==="bilateral")cv.bilateralFilter(m,r,9,75,75);showMat("p5out",type[0].toUpperCase()+type.slice(1)+" Filter",r);m.delete()}
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>spatial(b.dataset.filter));
let maskCanvas=$("maskCanvas"),maskCtx=maskCanvas.getContext("2d"),drawing=false;
function resetMask(){if(!state.img)return;maskCanvas.width=state.img.naturalWidth||state.img.width;maskCanvas.height=state.img.naturalHeight||state.img.height;maskCtx.drawImage(state.img,0,0,maskCanvas.width,maskCanvas.height)}
maskCanvas.onpointerdown=e=>{drawing=true;maskCtx.lineWidth=+$("brush").value;maskCtx.lineCap="round";maskCtx.strokeStyle="rgba(255,0,0,.9)";maskCtx.beginPath();maskCtx.moveTo(e.offsetX,e.offsetY)};
maskCanvas.onpointermove=e=>{if(drawing){maskCtx.lineTo(e.offsetX,e.offsetY);maskCtx.stroke()}};
window.onpointerup=()=>drawing=false;$("clearMask").onclick=resetMask;
document.querySelector('[data-inpaint="telea"]').onclick=()=>inpaint(false);document.querySelector('[data-inpaint="ns"]').onclick=()=>inpaint(true);
function inpaint(ns){if(!requireImage())return;clearOut("p6out");const src=baseMat(),mask=new cv.Mat(src.rows,src.cols,cv.CV_8UC1),tmp=maskCanvas.getContext("2d").getImageData(0,0,maskCanvas.width,maskCanvas.height).data;let d=mask.data;for(let i=0,j=0;i<tmp.length;i+=4,j++)d[j]=(tmp[i]>180&&tmp[i+1]<100)?255:0;const r=new cv.Mat();cv.inpaint(src,mask,r,3,ns?cv.INPAINT_NS:cv.INPAINT_TELEA);showMat("p6out",ns?"Navier–Stokes (NS)":"Telea",r);src.delete();mask.delete()}
$("compress").onclick=()=>{if(!requireImage())return;const c=makeCanvas(state.img.naturalWidth||state.img.width,state.img.naturalHeight||state.img.height),x=c.getContext("2d");x.drawImage(state.img,0,0,c.width,c.height);const a=x.getImageData(0,0,c.width,c.height).data;const bytes=new Uint8Array(a.length);for(let i=0;i<a.length;i++)bytes[i]=a[i];let runs=[],start=bytes[0],count=1;for(let i=1;i<bytes.length;i++){if(bytes[i]===start&&count<255)count++;else{runs.push([start,count]);start=bytes[i];count=1}}runs.push([start,count]);const original=bytes.length,compressed=runs.length*2,ratio=(compressed/original*100).toFixed(2);$("compressionStats").innerHTML=`<div class="stat">Original raw data<b>${original.toLocaleString()} bytes</b></div><div class="stat">RLE stream estimate<b>${compressed.toLocaleString()} bytes</b></div><div class="stat">Compressed size<b>${ratio}%</b><div class="bar"><span style="width:${Math.min(100,ratio)}%"></span></div></div><div class="stat">RLE runs<b>${runs.length.toLocaleString()}</b></div>`;$("rlePreview").textContent="First RLE pairs (value,run length):\\n"+runs.slice(0,80).map(r=>"("+r[0]+","+r[1]+")").join(" ")}
$("templateInput").onchange=e=>{const f=e.target.files[0];if(!f)return;$("templateName").textContent=f.name;const r=new FileReader();r.onload=x=>{const im=new Image();im.onload=()=>state.template=im;im.src=x.target.result};r.readAsDataURL(f)};
$("detect").onclick=()=>{if(!requireImage()||!state.template){alert("Choose a template image first.");return}if(!window.cv||!cv.Mat){alert("OpenCV.js is still loading. Wait a moment and try again.");return}clearOut("p9out");const src=baseMat(),tc=makeCanvas(state.template.naturalWidth||state.template.width,state.template.naturalHeight||state.template.height),tctx=tc.getContext("2d");tctx.drawImage(state.template,0,0,tc.width,tc.height);const templ=cv.imread(tc),res=new cv.Mat();if(templ.cols>src.cols||templ.rows>src.rows){alert("Template must be smaller than the scene image.");src.delete();templ.delete();return}cv.matchTemplate(src,templ,res,cv.TM_CCOEFF_NORMED);const mm=cv.minMaxLoc(res),pt=mm.maxLoc,display=makeCanvas(src.cols,src.rows);cv.imshow(display,src);const c=display.getContext("2d");c.strokeStyle="#ef4444";c.lineWidth=4;c.strokeRect(pt.x,pt.y,templ.cols,templ.rows);out("p9out","Correlation result — best match",display,`<p>Normalized correlation score: <b>${mm.maxVal.toFixed(4)}</b></p>`);src.delete();templ.delete();res.delete()};
function color(type){if(!requireImage())return;clearOut("p10out");const m=baseMat(),r=new cv.Mat();if(type==="rgb")cv.cvtColor(m,r,cv.COLOR_RGBA2RGB);if(type==="hsv")cv.cvtColor(m,r,cv.COLOR_RGBA2HSV);if(type==="ycrcb")cv.cvtColor(m,r,cv.COLOR_RGBA2YCrCb);if(type==="lab")cv.cvtColor(m,r,cv.COLOR_RGBA2Lab);showMat("p10out",type==="rgb"?"RGB":type==="hsv"?"HSV":type==="ycrcb"?"YCrCb":"Lab",r);m.delete()}
document.querySelectorAll("[data-color]").forEach(b=>b.onclick=()=>color(b.dataset.color));
function morph(type){if(!requireImage())return;clearOut("p8out");const m=baseMat(),g=new cv.Mat(),r=new cv.Mat();cv.cvtColor(m,g,cv.COLOR_RGBA2GRAY);cv.threshold(g,g,127,255,cv.THRESH_BINARY);const k=+$("morphKernel").value,K=cv.Mat.ones(k,k,cv.CV_8U);if(type==="erode")cv.erode(g,r,K);if(type==="dilate")cv.dilate(g,r,K);if(type==="open")cv.morphologyEx(g,r,cv.MORPH_OPEN,K);if(type==="close")cv.morphologyEx(g,r,cv.MORPH_CLOSE,K);showMat("p8out",type[0].toUpperCase()+type.slice(1),r);m.delete();g.delete();K.delete()}
document.querySelectorAll("[data-morph]").forEach(b=>b.onclick=()=>morph(b.dataset.morph));
function edge(type){if(!requireImage())return;clearOut("p11out");const m=baseMat(),g=new cv.Mat(),r=new cv.Mat();cv.cvtColor(m,g,cv.COLOR_RGBA2GRAY);if(type==="canny")cv.Canny(g,r,+$("cannyLow").value,+$("cannyHigh").value);else if(type==="sobel"){const sx=new cv.Mat(),sy=new cv.Mat();cv.Sobel(g,sx,cv.CV_64F,1,0,3);cv.Sobel(g,sy,cv.CV_64F,0,1,3);cv.magnitude(sx,sy,r);r.convertTo(r,cv.CV_8U);sx.delete();sy.delete()}else{const kx=cv.matFromArray(3,3,cv.CV_32F,[-1,0,1,-1,0,1,-1,0,1]),ky=cv.matFromArray(3,3,cv.CV_32F,[-1,-1,-1,0,0,0,1,1,1]),sx=new cv.Mat(),sy=new cv.Mat();cv.filter2D(g,sx,cv.CV_32F,kx);cv.filter2D(g,sy,cv.CV_32F,ky);cv.magnitude(sx,sy,r);r.convertTo(r,cv.CV_8U);kx.delete();ky.delete();sx.delete();sy.delete()}showMat("p11out",type==="canny"?"Canny Edge":type==="sobel"?"Sobel Edge":"Prewitt Edge",r);m.delete();g.delete()}
document.querySelectorAll("[data-edge]").forEach(b=>b.onclick=()=>edge(b.dataset.edge));
$("brush").oninput=()=>{$("brush").nextElementSibling.value=$("brush").value};

document.addEventListener("click", e=>{
 const b=e.target.closest("[data-op],[data-transform],[data-enhance],[data-filter],[data-inpaint],[data-morph],[data-color],[data-edge],#compress,#detect");
 if(!b)return;
 const panel=b.closest(".panel"); const code=panel?panel.id.replace("p",""):"unknown";
 const operation=b.dataset.op||b.dataset.transform||b.dataset.enhance||b.dataset.filter||b.dataset.inpaint||b.dataset.morph||b.dataset.color||b.dataset.edge||(b.id==="compress"?"RLE Compression":"Correlation Detection");
 recordExperiment(code,operation,$("fileName")?.textContent||"browser-image");
});
